# Generated by Django 4.0.6 on 2022-08-01 14:29

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='blog/categoty', verbose_name='Изображение'),
        ),
    ]
