# Generated by Django 4.0.6 on 2022-10-03 13:55

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_article_meta_description_article_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_preview',
            field=models.TextField(blank=True, verbose_name='Текст-превью'),
        ),
    ]
